import {register} from 'node:module';register('./three-module-loader.mjs',import.meta.url);
import assert from 'node:assert/strict';import fs from 'node:fs';
globalThis.self=globalThis;globalThis.createImageBitmap=async()=>({width:2048,height:2048,close(){}});
const T=await import('three'),{GLTFLoader}=await import('../docs/src/asset-loader.js'),{prepareStreetGeometry}=await import('../docs/src/street-indexed-geometry.js');
function original(source,matrix){let g=source.clone().applyMatrix4(matrix);if(g.index)g=g.toNonIndexed();for(const key of Object.keys(g.attributes))if(!['position','normal','uv'].includes(key))g.deleteAttribute(key);if(!g.attributes.uv)g.setAttribute('uv',new T.Float32BufferAttribute(new Float32Array(g.attributes.position.count*2),2));if(!g.attributes.normal)g.computeVertexNormals();return g}
let oldVertices=0,newVertices=0,triangles=0,meshes=0;
function check(source,matrix,count=false){const prior=original(source,matrix),next=prepareStreetGeometry(source,matrix),expanded=next.toNonIndexed();assert(next.index);for(const key of ['position','normal','uv'])assert.deepEqual(expanded.attributes[key].array,prior.attributes[key].array,'Exact per-corner '+key);if(count){oldVertices+=prior.attributes.position.count;newVertices+=next.attributes.position.count;triangles+=next.index.count/3;meshes++}prior.dispose();next.dispose();expanded.dispose()}
const bytes=fs.readFileSync(new URL('../docs/assets/web/scenes/lantern-street/lantern-street.glb',import.meta.url)),gltf=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
const metadata=JSON.parse(fs.readFileSync(new URL('../docs/assets/scenes/lantern-street/manifest.json',import.meta.url))),dynamic=new Set([...metadata.banners,...metadata.lights].map(s=>s.category));gltf.scene.updateMatrixWorld(true);gltf.scene.traverse(o=>{if(o.isMesh&&!dynamic.has(o.userData.category))check(o.geometry,o.matrixWorld,true)});
for(const indexed of [true,false])for(const normals of [true,false]){let g=new T.BoxGeometry();if(!indexed)g=g.toNonIndexed();if(!normals)g.deleteAttribute('normal');g.deleteAttribute('uv');check(g,new T.Matrix4().makeRotationY(.72).scale(new T.Vector3(2,1,3)));g.dispose()}
const report={passed:true,meshes,triangles,oldVertices,newVertices,reduction:1-newVertices/oldVertices,attributes:'Every triangle corner position, normal and UV is byte-identical to the previous batching path.'};console.log(report);
